#!/usr/bin/with-contenv bash

echo "**** install amd drivers ****"
echo "**** install ppa repos dependencies ****"
echo "**** apt-get update ****"
apt-get update
echo "**** install software-properties-common ****"
apt-get install -y software-properties-common
echo "**** add gpu driver repo ****"
add-apt-repository ppa:oibaf/graphics-drivers -y
echo "**** apt-get update ****"
apt-get update
echo "**** install vainfo, mesa-va-drivers, mesa-vdpau-drivers, libdrm-amdgpu1, libavutil56 ****"
apt-get install -y vainfo  mesa-va-drivers mesa-vdpau-drivers libdrm-amdgpu1 libavutil56
echo "**** copy driver libs to plex lib dir ****"
cp /lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so /usr/lib/plexmediaserver/lib/dri/ && \
cp /lib/x86_64-linux-gnu/libdrm_amdgpu.so.1.* /usr/lib/plexmediaserver/lib/libdrm_amdgpu.so.1 && \
cp /lib/x86_64-linux-gnu/libdrm.so.2.* /usr/lib/plexmediaserver/lib/libdrm.so.2 && \
cp /lib/x86_64-linux-gnu/libva-drm.so.2.* /usr/lib/plexmediaserver/lib/libva-drm.so.2 && \
cp /lib/x86_64-linux-gnu/libva.so.2.* /usr/lib/plexmediaserver/lib/libva.so.2 && \
cp /lib/x86_64-linux-gnu/libstdc++.so.6.* /usr/lib/plexmediaserver/lib/libstdc++.so.6 &&
